ALTER TABLE shops ADD COLUMN IF NOT EXISTS market_id INTEGER REFERENCES markets(id);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS category VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'pending';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE shops ADD COLUMN IF NOT EXISTS vendor_name VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
